### ISSUE TITLE
Using with Duende 

### ISSUE THREAD

**Issue by pvanroos** [mallibone/XamarinIdentity101#2]
Hi @mallibone ,

Using this example with Duende client that is configured for 'CodeFlowWithPkce'.  It returns a valid code, session_state, etc. after authentication but no AccessToken. 

Have i configured my client incorrectly?

**Comment by mallibone** [comment]
Hey @pvanroos, I hope you have solved your problem so far? (Aka, sorry for the late reply.)

If you are getting a valid code, you are halfway there. Since the initial response from the Identity Service (in your case, Duende) will reply a code. You can then get the Access Token (and the other tokens) by requesting it from the Token endpoint, which the OIDC client does automatically based on the reply of the IBrowser.

**Comment by pvanroos** [comment]
That's great.  Thanks @mallibone
